spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.12.51.41:3306/customer_service?serverTimezone=Asia/Shanghai
    username: root
    password: qaswedcvfrzx
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      validation-query: select 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: msg-management
  cloud:
    nacos:
      config:
        server-addr: 1.12.51.41:8848
        file-extension: yaml
      discovery:
        server-addr: 1.12.51.41:8848


server:
  port: 8081
  tomcat:
    threads:
      max: 200
      min-spare: 100