server:
  port: 8123

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 1.12.51.41:8848
        file-extension: yaml
      discovery:
        server-addr: 1.12.51.41:8848
    #路由配置
    gateway:
      routes:
        #表示websocket的转发
        - id: websocket-service
          uri: lb:ws://inst-msg
          predicates:
            - Path=/websocket/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true