server:
  port: 8084
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  freemarker:
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
  application:
    name: file-trans
  cloud:
    nacos:
      config:
        server-addr: 1.12.51.41:8848
        file-extension: yaml
      discovery:
        server-addr: 1.12.51.41:8848
rocketmq:
  # 指定namesrv地址
  name-server: 192.168.31.214:9876
  producer:
    #生产者group名称
    group: msg
    #一次发送多少数量消息
    max-message-size: 4096
    #发送消息超时时间,默认3000
    send-message-timeout: 3000
    #发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 2